### ISSUE TITLE
Workflows run-terraform.yml fails with "gke-gcloud-auth-plugin not found"

### ISSUE THREAD

**Issue by lislei** [kartverket/github-workflows#54]
When deploying to a Kubernetes cluster the workflow 
`kartverket/github-workflows/.github/workflows/run-terraform.yml@` fails with message "gke-gcloud-auth-plugin not found".

The solution is to bump this workflow to version v3.1.3 or newer. 

See [release notes v3.1.3](../releases/tag/v3.1.3)

**Comment by evenh** [comment]
Can this issue now be closed?
